# Generated by Django 4.2.7 on 2023-11-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bed', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('room_size', models.IntegerField()),
                ('room_view', models.CharField(max_length=255)),
                ('recommend', models.TextField()),
                ('price', models.CharField(max_length=255)),
                ('photo_main', models.ImageField(upload_to='photos/%Y//%m//%d/')),
                ('photo_1', models.ImageField(upload_to='photos/%Y//%m//%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%Y//%m//%d/')),
            ],
        ),
    ]
